# Label configuration for PR auto-labeling

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - '*.md'
      - '.github/**/*.md'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'pom.xml'
      - 'lib/**/*'

configuration:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/main/resources/**/*.yml'
      - 'src/main/resources/**/*.yaml'

feature:
  - changed-files:
    - any-glob-to-any-file: 'src/main/java/**/features/**/*'

listener:
  - changed-files:
    - any-glob-to-any-file: 'src/main/java/**/listener/**/*'

manager:
  - changed-files:
    - any-glob-to-any-file: 'src/main/java/**/manager/**/*'

gui:
  - changed-files:
    - any-glob-to-any-file: 'src/main/java/**/menu/**/*'

workflow:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**/*'

build:
  - changed-files:
    - any-glob-to-any-file:
      - 'pom.xml'
      - 'proguard*'
