# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en
tone_instructions: |
  Be constructive and helpful. Focus on code quality, performance, and maintainability. 
  Highlight security concerns. Suggest improvements with specific examples. 
  Enforce the NO COMMENTS rule strictly for Java files.
early_access: true
reviews:
  profile: assertive
  request_changes_workflow: true
  collapse_walkthrough: false
  labeling_instructions:
    - label: bug
      instructions: Apply when fixing a defect or error in existing functionality
    - label: feature
      instructions: Apply when adding new functionality or capabilities
    - label: documentation
      instructions: Apply when only changing documentation files
    - label: performance
      instructions: Apply when optimizing code performance
    - label: security
      instructions: Apply when addressing security vulnerabilities
    - label: breaking-change
      instructions: Apply when changes break backwards compatibility
  poem: false
  path_filters:
    - "!target/**"
    - "!*.class"
    - "!*.jar"
    - "!dependency-reduced-pom.xml"
    - "!proguard*"
    - "!docs/build/**"
    - "!docs/node_modules/**"
    - "!.vscode/**"
    - "!.git/**"
  path_instructions:
    - path: src/main/java/**/*.java
      instructions: |
        CRITICAL PROJECT RULES:
        - NO COMMENTS in production code (code must be self-documenting)
        - Clean, descriptive method and variable names required
        - Features MUST be modular and toggleable via config
        - Package structure: com.tejaslamba.vanillacore.[feature].[type]
        - Proper error handling and null checks required
        - Check for memory leaks (proper cleanup on player quit)
        - Thread-safety where needed (ConcurrentHashMap for concurrent access)
        - Early returns in event listeners for performance
    - path: src/main/resources/config.yml
      instructions: |
        - All new features MUST have enabled: false by default
        - Config options must be well-documented in comments
        - Update config-version if structure changes
        - Consistent indentation and structure
    - path: docs/**/*.md
      instructions: |
        - Documentation must be clear and accurate
        - All features must be properly documented
        - Examples must be correct and tested
        - Verify all links are working
    - path: CHANGELOG.md
      instructions: |
        - Follow Keep a Changelog format strictly
        - All changes must be documented
        - NO hallucinated features - verify against actual code
        - Correct version numbers
  auto_review:
    base_branches:
      - main
  tools:
    shellcheck:
      enabled: false
    ruff:
      enabled: false
    biome:
      enabled: false
    hadolint:
      enabled: false
    swiftlint:
      enabled: false
    phpstan:
      enabled: false
    phpmd:
      enabled: false
    phpcs:
      enabled: false
    golangci-lint:
      enabled: false
    eslint:
      enabled: false
    flake8:
      enabled: false
    rubocop:
      enabled: false
    pylint:
      enabled: false
    oxc:
      enabled: false
knowledge_base:
  code_guidelines:
    filePatterns:
      - .github/copilot-instructions.md
      - CONTRIBUTING.md
  learnings:
    scope: global
issue_enrichment:
  labeling:
    auto_apply_labels: true
