name: VanillaCore
main: com.tejaslamba.vanillacore.Main
version: ${project.version}
api-version: ${minecraft.version}
softdepend: [WorldGuard]
commands:
  vanilla:
    description: Vanilla Core command
    usage: /vanilla [menu|reload|enchant|mace|netherite|infiniterestock]
    aliases: [vc, vpt]
  end:
    description: End dimension lock commands
    usage: /end [open|close|status]
  nether:
    description: Nether dimension lock commands
    usage: /nether [open|close|status]
permissions:
  vanillacore.admin:
    description: Full access to all Vanilla Core features and GUI
    default: op
    children:
      vanillacore.reload: true
      vanillacore.menu: true
      vanillacore.enchant: true
      vanillacore.mace: true
      vanillacore.mace.reset: true
      vanillacore.dimension.end: true
      vanillacore.dimension.nether: true
      vanillacore.dimension.bypass: true
      vanillacore.netherite: true
      vanillacore.infiniterestock: true
  vanillacore.reload:
    description: Reload plugin configuration
    default: op
  vanillacore.menu:
    description: Open settings menu
    default: op
  vanillacore.enchant:
    description: Manage enchantment limits
    default: op
  vanillacore.mace:
    description: Use mace commands
    default: op
  vanillacore.mace.reset:
    description: Reset mace limiter
    default: op
  vanillacore.dimension.end:
    description: Manage end dimension lock
    default: op
  vanillacore.dimension.nether:
    description: Manage nether dimension lock
    default: op
  vanillacore.dimension.bypass:
    description: Bypass all dimension locks
    default: op
  vanillacore.dimension.bypass.end:
    description: Bypass end dimension lock
    default: false
  vanillacore.dimension.bypass.nether:
    description: Bypass nether dimension lock
    default: false
  vanillacore.netherite:
    description: Manage netherite disabler
    default: op
  vanillacore.infiniterestock:
    description: Manage Infinite Restock feature and open GUI
    default: op
  vanillacore.netherite.craft.*:
    description: Bypass netherite crafting restrictions
    default: false
