name: Vanilla Core
main: com.tejaslamba.vanillacore.Main
version: 1.2.1
api-version: 1.21
softdepend: [WorldGuard]
commands:
  smp:
    description: Vanilla Core command
    usage: /smp [menu|reload|enchant|mace|netherite|infiniterestock]
    aliases: [vpt]
  end:
    description: End dimension lock commands
    usage: /end [open|close|status]
  nether:
    description: Nether dimension lock commands
    usage: /nether [open|close|status]
permissions:
  vanillacore.reload:
    description: Reload plugin configuration
    default: op
  vanillacore.menu:
    description: Open settings menu
    default: op
  vanillacore.enchant:
    description: Manage enchantment limits
    default: op
  vanillacore.mace:
    description: Use mace commands
    default: op
  vanillacore.mace.reset:
    description: Reset mace limiter
    default: op
  vanillacore.dimension.end:
    description: Manage end dimension lock
    default: op
  vanillacore.dimension.nether:
    description: Manage nether dimension lock
    default: op
  vanillacore.dimension.bypass:
    description: Bypass all dimension locks
    default: op
  vanillacore.dimension.bypass.end:
    description: Bypass end dimension lock
    default: false
  vanillacore.dimension.bypass.nether:
    description: Bypass nether dimension lock
    default: false
  vanillacore.netherite:
    description: Manage netherite disabler
    default: op
  vanillacore.infiniterestock:
    description: Manage Infinite Restock feature and open GUI
    default: op
  vanillacore.netherite.craft.*:
    description: Bypass netherite crafting restrictions
    default: false
